server {
    listen 80;

    location /rest/v1/ {
        rewrite ^/rest/v1/(.*)$ /$1 break;
        proxy_pass http://supabase-rest:3000;
        proxy_set_header Host             $host;
        proxy_set_header Authorization    $http_authorization;
        proxy_set_header apikey           $http_apikey;
        proxy_set_header Content-Type     $http_content_type;
        proxy_set_header Prefer           $http_prefer;
    }
}
